# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='genere',
            new_name='genre',
        ),
    ]
